version: "3.9"

networks:
  proxy:
    driver: bridge

services:
  bma-proxy:
    image: haproxy:2.7-alpine
    container_name: bma-proxy
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
      - 9000:9000
    networks:
      - proxy

  bma-api1:
    container_name: bma-api
    build:
      context: ./services/api
    command: yarn start
    networks:
      - proxy
    environment:
      - PORT=8080
  
  bma-api2:
    container_name: bma-api2
    build:
      context: ./services/api
    command: yarn start
    networks:
      - proxy
    environment:
      - PORT=8081
  
  bma-api3:
    container_name: bma-api3
    build:
      context: ./services/api
    command: yarn start
    networks:
      - proxy
    environment:
      - PORT=8083
