version: "3.9"

networks:
  proxy:
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local

services:
  reverse-proxy: 
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    links:
      - bma-main:bma-main
      - bma-account:bma-account
      - bma-payment:bma-payment
      - bma-social:bma-social
    networks:
      - proxy
    
  bma-main:
    container_name: bma-main
    build: 
      dockerfile: ./packages/main/Dockerfile
    image: bma-main:latest
    command: yarn start	
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    networks:
      - proxy
  
  bma-account:
    container_name: bma-account
    build: 
      dockerfile: ./packages/account/Dockerfile
    image: bma-account:latest
    command: yarn start	
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=BMARedis
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    networks:
      - proxy
  
  bma-payment:
    container_name: bma-payment
    build: 
      dockerfile: ./packages/payment/Dockerfile
    image: bma-payment:latest
    command: yarn start	
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    networks:
      - proxy
  
  bma-social:
    container_name: bma-social
    build: 
      dockerfile: ./packages/social/Dockerfile
    image: bma-social:latest
    command: yarn start	
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    networks:
      - proxy
  
  db:
    container_name: bma-database
    image: postgres:alpine
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - proxy
  
  cache:
    container_name: bma-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass BMARedis
    volumes:
      - cache:/data
    networks:
      - proxy
