version: "3.9"

networks:
  proxy:
    driver: bridge

services:
  nginx: 
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - proxy
    
  bma-main:
    container_name: bma-main
    build: 
      dockerfile: ./packages/main/Dockerfile
    image: bma-main:latest
    networks:
      - proxy
  
  bma-account:
    container_name: bma-account
    build: 
      dockerfile: ./packages/account/Dockerfile
    image: bma-account:latest
    networks:
      - proxy
  
  bma-payment:
    container_name: bma-payment
    build: 
      dockerfile: ./packages/payment/Dockerfile
    image: bma-payment:latest
    networks:
      - proxy
  
  bma-social:
    container_name: bma-social
    build: 
      dockerfile: ./packages/social/Dockerfile
    image: bma-social:latest
    networks:
      - proxy
